name: pr branch jobs
on: [pull_request]
jobs:
  development:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Go Tooling Preparation
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          cache: true
      - run: go vet ./...
      - run: go build ./...
      - run: go test ./...
      - run: go run .
